### PR TITLE
feature/por-message

### PR DESCRIPTION
**Pull request by haavarol**
Before I opened this Pull Request, I have:

- [x] written 📝 code documentation where it made sense
- [ ] written tests 🔬, where it was necessary
- [x] updated the `CHANGELOG.md` file 📝
- [x] referenced all the issues in commits related to this PR

according to my best knowledge.

### CODE REVIEW

**Review by balazsorban44 — COMMENTED** [review]
Nice work. I would wait until we figure out if we can test it before merging into `develop`. @Virkz do you have any progress on testing?

**Comment by PetterRein** [comment]
I will today ;-)

**Comment by haavarol** [comment]
Backend will be squished and abandoned. Merge please :)

**Review by PetterRein — APPROVED** [review]
Very good. The test in messages is wrong. But will be overwriten by more-test branch

**Pull request merged**
